version: '3'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: database-1.cvywwg4swlx6.sa-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: a1234578
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /mnt/efs/wp-content:/var/www/html/wp-content
